### ISSUE TITLE
firewall disabling?

### ISSUE THREAD

**Issue by bengland2** [batrick/ceph-linode#33]
with ceph-ansible stable-3.1 branch I found this necessary at end of pre-config.yml:

```
- hosts: all
  become: yes
  tasks:
  - name: disable firewall
    shell: "(systemctl stop firewalld && systemctl disable firewalld) || (systemctl stop iptables && systemctl disable iptables)"
```
but maybe newer version of ceph-ansible handles this now?
